#!/usr/bin/env bash

function makepost
{
cat <<EOF > $2
---
title: $1
tags:
---
EOF
}

if [ $# -gt 0 ]
then
    TITLE=$@
    # Convert everything to lower case ASCII (removes accents)
    SLUG=`tr '[:upper:] ' '[:lower:]-' <<< ${TITLE} | iconv -f utf8 -t ascii//TRANSLIT`
    FILENAME=drafts/2000-01-01-$SLUG.markdown
    if [ ! -e $FILENAME ]
    then
        makepost "${TITLE}" "${FILENAME}"
    fi
    # Open editor at text 'tags' ready to insert a tag
    vim +/tags ${FILENAME}
fi
