#!/usr/bin/env bash

if [ "$1" = "" ];
then
    echo "usage: publish path/to/draft.markdown"
    exit 1
fi

if [ -e $1 ]
then
    DATE=$(date +'%F')
    POST=$(basename $1)
    PUBLISHED=$DATE-$POST

    # If the draft post is already being tracked just let git
    # move it. Otherwise move it then add to the index.
    if git ls-files --error-unmatch drafts/$POST
    then
        git mv drafts/$POST posts/$PUBLISHED
    else
        mv drafts/$POST posts/$PUBLISHED
        git add posts/$PUBLISHED
    fi
    echo $PUBLISHED > .justpublished

    echo "Post published on $DATE"
else
    echo "File $1 cannot be found"
fi
