#!/usr/bin/env bash

if [ "$1" = "" ];
then
    echo "usage: publish path/to/draft.markdown"
    exit 1
fi

if [ -e $1 ]
then
    DATE=$(date +'%F')
    POST=$(basename $1)

    # Starting at the 12th character, omitting the fake date
    # before we insert the real one.
    SLUG=$(basename $1 | cut -c 12-)
    PUBLISHED=$DATE-$SLUG

    # If the draft post is already being tracked just let git
    # move it. Otherwise move it then add to the index.
    # We get a scary warning if we don't redirect to null.
    if git ls-files --error-unmatch drafts/$POST > /dev/null 2>&1
    then
        git mv drafts/$POST posts/$PUBLISHED
    else
        mv drafts/$POST posts/$PUBLISHED
        git add posts/$PUBLISHED
    fi
    echo $PUBLISHED > .justpublished

    echo "Post published on $DATE"
else
    echo "File $1 cannot be found"
fi
