#!/usr/bin/env bash

RECENT=.justpublished

if [ -e $RECENT ]
then
    PUBLISHED=$(cat $RECENT)
    
    if [ ! -e posts/$PUBLISHED ];
    then
        echo "Cannot find just-published file $PUBLISHED"
        exit 1
    fi
    DRAFT=$(basename $PUBLISHED)
    git mv posts/$PUBLISHED drafts/$DRAFT
    echo "Post back in drafts as $DRAFT"
    rm $RECENT
else
    echo "No recently published file in $RECENT?"
fi
